### ISSUE TITLE
Because every version of fl_kdxf_sst_rt depends on permission_handler ^10.2.0

### ISSUE THREAD

**Issue by hbalxzdl** [ssh199956/fl_kdxf_sst_rt#1]
Because every version of fl_kdxf_sst_rt depends on permission_handler ^10.2.0 and school_app depends on permission_handler ^11.0.1, fl_kdxf_sst_rt is forbidden.
So, because school_app depends on fl_kdxf_sst_rt any, version solving failed.

**Comment by ssh199956** [comment]
OK, I have received your request and I will update it as soon as possible. If you need it urgently, you can update it manually first, or you can join us to jointly maintain this library.

**Comment by ssh199956** [comment]
i have updated.You can try again.
